### ISSUE TITLE
how to run the client and renderer on different ECU?

### ISSUE THREAD

**Issue by zeerd** [GENIVI/ramses#10]
I have two ECUs. And
Run daemon on ECU0 without any parameter.
Run renderer on ECU1 with parameter sid/lid/i.

When I run client on ECU1, with parameter i, it works fine.
When I run client on ECU0, with paramter i, it could not work.

As my mind, the client could run on a different ECU from renderer. So if my understanding is right, there must be some other paramters I should use when I run the client on ECU0, I think. 
But I am not sure what it is. I am confused between the codes 😢

**Comment by GENIVI-Ramses** [comment]
Hello zeerd,
Of course, the client can run on a different ECU - that is the main feature of RAMSES ;)
In order to connect them, you have to configure all components (client, daemon, renderer) with each others' IP addresses. I suspect the issue you are facing is that the client's own IP address is different when you run it on ECU0 rather than ECU1, and that's why it doesn't work. When all components run on the same ECU, they all get the default "localhost" address, so they can connect. If you run them on different ECUs, you have to configure their IPs explicitly and the IP of the daemon, because RAMSES' TCP stack doesn't have an autodiscover feature. The commands could look like this (executed on different ECUs ofcourse):
# ECU0 (local IP is 192.168.1.1)
./ramses-client --myipaddress 192.168.1.1 --daemon-ip 192.168.1.1
./ramses-daemon --myipaddress 192.168.1.1
#ECU1 (local IP is 192.168.1.2)
./ramses-renderer --myipaddress 192.168.1.2 --daemon-ip 192.168.1.1

If my example didn't work for you, could you provide the log outputs of each component? They are quite verbose about who could connect, who are the participants, is there a scene available etc.

**Comment by GENIVI-Ramses** [comment]
Just added a new Wiki page with more detailed description how to run in a distributed setup: https://github.com/GENIVI/ramses/wiki/Running-the-examples

**Comment by zeerd** [comment]
Thank you.
I am busying on other things those days. I will try it later, but close this now.
