### ISSUE TITLE
Version missing, Protocol Version not very prominent

### ISSUE THREAD

**Issue by ManuelKugelmann** [GENIVI/ramses#37]
I often get compatibility issues with various ramses based systems and most I see only at runtime ...

**Comment by tohammer** [comment]
You are right, there is currently no compatibility and the version check is not working because everything is always 0.0.0.
Up to now we only shipped from development branch but we plan to align oss releases with our regular version scheme. Then the version checks should work and you can chose compatible version based on version number beforehand.

**Comment by tohammer** [comment]
From https://github.com/GENIVI/ramses/commit/0283230a5aa91ba336d279490a562554abcc6a3f on we use regular versions on releases with guaranteed compatibility between patch releases
