### ISSUE TITLE
textureType is inaccessible

### ISSUE THREAD

**Issue by martin-hackenberg-paradoxcat** [GENIVI/ramses#40]
For dynamic detection of uniform texture type (e.g. sampler2d or cubeMap) it would be useful to have this information available in the EffectInput.

**Comment by GENIVI-Ramses** [comment]
Makes sense! Two questions though: you say "EffectInput" but you actually mean "UniformInput", right? EffectInput can be also an attribute, so can't expose texture types there.
Second question: Would it be acceptable to extend the EEffectInputDataType enum so that instead of having a single "texture" type, it has several:
EEffectInputDataType::EEffectInputDataType_TextureSampler2D
EEffectInputDataType::EEffectInputDataType_TextureSampler3D
EEffectInputDataType::EEffectInputDataType_TextureSamplerCube

**Comment by martin-hackenberg-paradoxcat** [comment]
Yes, i mean "UniformInput". The suggested approach would be fine.

**Comment by tohammer** [comment]
We solved this as already suggested by splitting
```
EEffectInputDataType_TextureSampler
```
```
EEffectInputDataType_TextureSampler2D,
EEffectInputDataType_TextureSampler3D,
EEffectInputDataType_TextureSamplerCube
```
Will be included in next major version 26

**Comment by tohammer** [comment]
EEffectInputDataType was extended with the new enum values with  https://github.com/GENIVI/ramses/releases/tag/26.0.2
