### ISSUE TITLE
Assert in debug when using example geometry shader

### ISSUE THREAD

**Issue by AchimStremplat** [GENIVI/ramses#49]
Using the geometry shader in debug provided in the geometry shader example leads to an assert in Device_GL::validateDeviceStatusHealthy().

To reproduce the issue in Ramses Composer, you need to rename the mvpMatrix uniform in the vertex shader to u_MVPMatrix, and the a_position attribute to a_Position.

**Comment by violinyanev** [comment]
Hi Achim!

We analyzed the issue, and it has 2 sides:
- the example geometry shader expects points as incoming geometry, but the composer provides triangles -> this triggers the assert
- ramses cliet doesn't catch the error, so there is no way of knowing that the given geometry shader must be paired with a geometry of a specific type

Will prepare a fix for ramses, but might take a while because not trivial to implement. Until then I'm afraid the geometry shader feature can't be robustly implemented, other than replace the assert in the renderer with "ignore and draw the rest"

**Comment by AchimStremplat** [comment]
Thanks for the info! For the debug version we can ignore the assert for now.

Would it be easily possible to log a one-off error message in release? Currently the release version does not log/report any error as far as I can see? 
Of course we also want to avoid an error message each time the scene is rendered, so if an one-off error message is not easily possible, it might be best to leave it as is until a proper fix can be implemented (given that the error conditions to me don't seem to be something which will occur very often during normal use)?

**Comment by tohammer** [comment]
This issue is fixes for dynamically created scenes with https://github.com/GENIVI/ramses/releases/tag/27.0.100 release.
Also fixing it for scenes loaded from file is planned for 28 because it requires breaking changes.
